// Generated by https://quicktype.io

export interface Configuration {
 baseURL: string;
 weather: Weather;
}

export interface Weather {
 URL: string;
 key: string;
}

export const environment = {
 configURL: 'configuration.json'
}